### ISSUE TITLE
Can't enable deoplete

### ISSUE THREAD

**Issue by marcus** [Shougo/deoplete.nvim#167]
`echo has("python3")` returns 1

`UpdateRemotePlugins` returns `remote/host: python3 host registered plugins ['unite.py', 'deoplete.py']`

Restarting neovim then running DeopleteEnable still says deoplete.nvim is not registered.

`:version`
`NVIM 0.1.2
Build type: RelWithDebInfo
Compilation: /usr/local/Library/ENV/4.3/clang -Wconversion -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neo
vim20160212-9986-9ttzm2/neovim-0.1.2/build/config -I/tmp/neovim20160212-9986-9ttzm2/neovim-0.1.2/src -I/tmp/neovim20160212-9986-9ttzm2/neovim-0.1.2/deps-build/usr/include -I/tmp/neovim20160212-9986-9ttzm2/neovim-0.1.2/deps-build/usr/include -I/tmp/neovim20160212-9986-9ttz
m2/neovim-0.1.2/deps-build/usr/include/luajit-2.0 -I/tmp/neovim20160212-9986-9ttzm2/neovim-0.1.2/deps-build/usr/include -I/tmp/neovim20160212-9986-9ttzm2/neovim-0.1.2/deps-build/usr/include -I/tmp/neovim20160212-9986-9ttzm2/neovim-0.1.2/deps-build/usr/include -I/tmp/neovi
m20160212-9986-9ttzm2/neovim-0.1.2/deps-build/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include -I/tmp/neovim20160212-9986-9ttzm2/neovim-0.1.2/build
/src/nvim/auto -I/tmp/neovim20160212-9986-9ttzm2/neovim-0.1.2/build/include
`

**Comment by Shougo** [comment]
I think it is same problem.

https://github.com/Shougo/deoplete.nvim/issues/160

I don't know why rc-plugin is not loaded.

**Comment by Shougo** [comment]
@marcus It may be neovim bug.
Please execute below command.

```vim
echo fnamemodify(expand($MYVIMRC, 1), ':h')
      \.'/.'.fnamemodify($MYVIMRC, ':t').'-rplugin~'
```

And check the file exists.

**Comment by theamazingfedex** [comment]
At one point in the past, I was getting errors about multiple init files from the init.vim-rplugin~ file, so I put a line in at the bottom of my vimrc to delete the file, which stopped me getting that error.
Since that file seems to be needed for some plugins, I just removed that line to delete the file, and since I updated Neovim recently I don't get the multiple init file error, AND I don't need to add in the manual remote plugin registration anymore, it just works.

My suggestion for @marcus, or others having the same issue, would be to try updating your neovim to the head revision, make sure there's nothing too hacky and archaic in your vimrc/init.vim, and if it's still not working, try manually registering the plugin in your vimrc/init.vim, like so:
````vim
call remote#host#RegisterPlugin('python3', '/Users/shougo/.vim/bundle/deoplete.nvim/rplugin/python3/deoplete.py', [
      \ {'sync': 1, 'name': 'DeopleteInitializePython', 'type': 'command', 'opts': {}},
     \ ])
````

**Comment by Shougo** [comment]
@theamazingfedex Thank you for the advice!

**Comment by tcuthbert** [comment]
I am having the same issue, @theamazingfedex answer doesn't resolve the issue and I am using neovim HEAD installed from Linux brew on Fedora 23.

Is there any more tips for a workaround?

**Comment by Shougo** [comment]
No response.
I think the problem is solved.
