### ISSUE TITLE
Utf-8 error "invalid continuation byte" when there's a tags file in the directory

### ISSUE THREAD

**Issue by marlun** [Shougo/deoplete.nvim#17]
I'm getting the following error when I've got a tags file in my folder:

```
Traceback (most recent call last):
  File "/Users/marlun/.nvim/bundle/deoplete.nvim/rplugin/python3/deoplete/__init__.py", line 78, in completion_begin
    candidates = self.deoplete.gather_candidates(context)
  File "/Users/marlun/.nvim/bundle/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 99, in gather_candidates
    self.vim, context)
  File "/Users/marlun/.nvim/bundle/deoplete.nvim/rplugin/python3/deoplete/sources/tag.py", line 42, in gather_candidates
    for l in tags_file.readlines():
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/codecs.py", line 319, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe5 in position 6493: invalid continuation byte
```

I've updated and compiled latest neovim and deoplete and I've run UpdateRemotePlugins.

If I remove my tags file and disable https://github.com/ludovicchabant/vim-gutentags (which otherwise will regenerate it) everything is working fine.

If I have gutentags installed and enabled and it regenerates the tags file, as soon as it's done I get the error message above (multiple times).

OS: OS X Yosemite 10.10.3
Neovim commit: 7b87dc9299993003ea9cd2e0f0f38b881010501d

**Comment by HerringtonDarkholme** [comment]
This probably a problem with python's encoding and your tag file, not a problem with deoplete/neovim.

Can you try reading your tag files in python3?

Besides that, tag source is too slow for large or medium project. I can feel significant delay(complete menu does not popup several seconds after key stroke) if tags file is ten thousands line long.

**Comment by marlun** [comment]
@HerringtonDarkholme any tips on how I should test that? I tried just doing

```python
open './tags' as tags_file:
    print("test")
```

and it gives me no errors.

> Besides that, tag source is too slow for large or medium project. I can feel significant delay(complete menu does not popup several seconds after key stroke) if tags file is ten thousands line long.

Can I disable it somehow?

**Comment by ZyX-I** [comment]
@marlun When you open file Python does not read it (BTW are you sure this is Python: `open '/dev/null' as dn:` gives me SyntaxError (IPython 2.4.1 on top of Python 3.4.1)?). Since it does not read it it does not throw UnicodeDecodeError. You need to use `open('./tags').read()` to test: this construct will read the whole file.

**Comment by marlun** [comment]
Thanks, now I'm getting the error:

```
$ python3 test.py
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    tags = open('./tags').read()
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/codecs.py", line 319, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe5 in position 247216485: invalid continuation byte
```

So, do you think it's an error with the generated tags file so that I should create an issue on https://github.com/fishman/ctags instead?

>  (BTW are you sure this is Python: open '/dev/null' as dn: gives me SyntaxError (IPython 2.4.1 on top of Python 3.4.1)?)

I took that code from `/Users/marlun/.nvim/bundle/deoplete.nvim/rplugin/python3/deoplete/sources/tag.py`.

**Comment by ZyX-I** [comment]
I do not know what encoding this file *should* be. Maybe it is indeed error in deoplete which for some reason assumed that Python (that assumes utf-8) can deduce the proper encoding.

**Comment by marlun** [comment]
I don't see why the tags file wouldn't be utf-8 though. Am I understanding it correctly that Python is saying that the tags file is not utf-8?

**Comment by ZyX-I** [comment]
@marlun What happens if file for which tags file is generated is in ASCII-compatible non-UTF-8 encoding? Some languages (at least, Python-3.4) allow non-unicode identifiers\*, most allow non-unicode strings and *ctags can be configured to use regex in place of line number*. Regex is usually the whole line or “most significant” part of line. Also what *should happen* in this case?

I think that most likely ctags includes such lines “as-is” (without converting encoding). If this is true and this is not against tags file spec then there is error in *deoplete* that needs to be fixed: such files should be read in binary mode. Note that `man ctags` contains exactly *no* references to the word “encoding”.

\* The following code works in Python-3.4:

```Python
# vim: set fileencoding=cp1251
testабц = 'деф'

print(testабц)
```

(save in CP1251 encoding, comment is significant).

**Comment by Shougo** [comment]
> Can I disable it somehow?

No.  This feature is not implemented.

I think tag source should catch the UnicodeError.

**Comment by Shougo** [comment]
> Besides that, tag source is too slow for large or medium project. I can feel 
significant delay(complete menu does not popup several seconds after key stroke) if tags file is ten thousands line long.

I think the cache source should implement cache feature.

**Comment by Shougo** [comment]
Fixed the error problem.
