### ISSUE TITLE
Having trouble with installation instructions

### ISSUE THREAD

**Issue by monicao** [Shougo/deoplete.nvim#236]
I am new to neovim. Could you please provide more detailed instructions for how to install the plugin?

From the README instructions:

> Extract the files and put them in your Neovim directory (usually ~/.config/nvim).

Which files should be extracted? Displaying a sample file structure would be really helpful.

Thanks!

**Comment by fmoralesc** [comment]
Hi, @monicao.

Vim/Neovim plugins are usually distributed in a way so you can just drop your files in what it's called the "runtimepath" (basically, a list of directories (n)vim will look for files into). The runtimepath typically includes `~/.config/nvim/` in Neovim's case. So in the most typical scenario, if the plugin has this layout:
~~~
plugin/
    myplugin.vim
rplugin/
    python3/
       pythonmodule.py
README.md
~~~
you should copy all of those files to the `~/.config/nvim/` folder, so you will end up with
~~~
~/
    .config/
        nvim/
           plugin/
               myplugin.vim
           rplugin/
              python3/
                pythonmodule.py
           README.md
~~~
If you are using a plugin manager ([vim-plug](https://github.com/junegunn/vim-plug/) is recommended for its simplicity, @Shougo's [dein.vim](https://github.com/shougo/dein.vim) is also good but somewhat more complicated), you can simply drop all files in their own directory inside a special folder (typically called "bundles"). So you will have:
~~~
~/
    .config/
        nvim/
            bundles/
                myplugin/
                    plugin/
                        myplugin.vim
                    rplugin/
                        python3/
                            pythonmodule.py
                    README.md
~~~
This kind of layout is very useful when you have multiple plugins, since their files are neatly separated.

**Comment by monicao** [comment]
Thanks @fmoralesc that's really helpful.

@Shougo I realize there are many ways to install vim plugins and deoplete's README can't cover them all. Perhaps you can add a link to @fmoralesc's comment in the README for noobs like me.

**Comment by DarkDefender** [comment]
@monicao It is alot easier to install if you are using a plugin manager like https://github.com/junegunn/vim-plug for example. It is also easy to update or uninstall plugins this way.
