### ISSUE TITLE
[README] Add single-line plugin-manager installation recommendation

### ISSUE THREAD

**Issue by malteneuss** [Shougo/deoplete.nvim#249]
# Problems summary
The README.md should provide installation recommendations for the widespread plugin-managers
such as vundle, neobundle and vim-plug,  which can safely be copied into the users .vimrc.
E.g. 
```
vim-plug:
Plug 'Shougo/deoplete.nvim' { 'do': 'UpdateRemotePlugins', 'do': 'pip3 install neovim' }
```
I don't know if this specific example would fail or not but it would make installing deoplete a lot easier for people new to vim like me.

Best regards,
malte

**Comment by wsdjeg** [comment]
pip neovim is not vim plugin,I do not think let vim plugin manager do everything is a good idea.pip install neovim,is just installing the python client of neovim,not only for deoplete.It make neovim support python

**Comment by tweekmonster** [comment]
Yes, what @wsdjeg said is correct.  The neovim python-client is something the user needs to manually deal with.

There are many situations where your example simply won't work, particularly if `pip3` is owned by root, or if `pip3` doesn't exist at all.  It would lead to more issues being created stating that the instructions were wrong.  It would be nice if neovim included the python-client as part of the releases, though.  As it stands now, every plugin that uses neovim's python-client would need the same boilerplate instructions.

I started working on a wiki page for this because [deoplete-jedi](https://github.com/zchee/deoplete-jedi) had a few issues opened due to a misunderstanding of how Python is used with neovim.  It's incomplete and will need to address other Python installation scenarios.  Hope you find it useful: https://github.com/zchee/deoplete-jedi/wiki/Setting-up-Python-for-Neovim

**Comment by monkoose** [comment]
@tweekmonster Why we should create another venv for neovim? I just pointed `let g:python3_host_prog` to my /usr/bin/python3. And it works great.

**Comment by wsdjeg** [comment]
@monkoose what `venv` is ?

**Comment by wsdjeg** [comment]
do you mean `virtual environment`,we do not create any `virtual environment`,neovim use magpack api comunicate with the client,and `pip neovim` is just  a python client for neovim.

**Comment by tweekmonster** [comment]
@monkoose There's no problem with how you're doing it.  The wiki page is intended for `deoplete-jedi` users and I was using it as an example of why having a single-line "pip install neovim" note in the README wouldn't work.  It needs to be updated with a section for light Python development so it can be used as reference or any user.

@wsdjeg If you work on many Python projects, virtualenv allows you to have different environments for Python packages.  Certain projects have package requirements that are incompatible with other projects.  There also have been some users that installed `neovim` into each environment because they don't know they can have a dedicated environment for neovim.

The reason I use virtualenv is neovim's python-client installs third party packages.  It could cause unexpected upgrades if those packages were a requirement of one of my projects.  I personally prefer to keep the system Python installation free of packages from PyPI for the same reason: stable system packages may require specific versions of Python packages.  The wiki page is opinionated based on my experience and needs to be updated for a broader audience.

**Comment by monkoose** [comment]
I just didn't read full wiki from his link, and there is part about my question https://github.com/zchee/deoplete-jedi/wiki/Setting-up-Python-for-Neovim#why-you-shouldnt-use-sudo.

**Comment by malteneuss** [comment]
Ok, i understand that installing neovim python package depends on too many other factors to be a single-line recommendation, but what about the following note after the user was told to install python 
```
vim-plug:
Plug 'Shougo/deoplete.nvim' { 'do': 'function(UpdateRemotePlugins)' }
```
To me, presenting these examples seems standard practice for many vim plugins.
And as i understand, in some cases 'remote plugins' have to be updated(which is totally under neovim's control) after updating deoplete. Why not mention a hook that does this automatically everytime deoplete is updated?

**Comment by wsdjeg** [comment]
@tweekmonster thanks 

now I install neovim by building form source,just run 
```
make
sudo make install
```
then 

```sh
pip install --user neovim  ## here my pip -V output pip 8.1.1 from /usr/lib/python3.5/site-packages (python 3.5)
pip2 install --user neovim
```

then add to vimrc
```vim
let g:python_host_prog = '/usr/bin/python2'
let g:python3_host_prog = '/usr/bin/python3'  " here I can use let g:python3_host_prog = '/usr/bin/python'  because my python --version is 3.5
```

```

**Comment by tweekmonster** [comment]
Thanks @monkoose and @wsdjeg for your perspectives.  I've updated the wiki page to be more informative: https://github.com/zchee/deoplete-jedi/wiki/Setting-up-Python-for-Neovim

@malteneuss Your example is in the doc under the FAQ, but it could use some language treatment since Shougo isn't a native English speaker.
