### ISSUE TITLE
neovim-client version detection

### ISSUE THREAD

**Issue by standeck** [Shougo/deoplete.nvim#435]
Hello, thanks for this plugin.

I have a question about neovim-client version detection: https://github.com/Shougo/deoplete.nvim/blob/master/rplugin/python3/deoplete/__init__.py#L28-L42.

What is the reason of so difficult instead of using VERSION variable from neovim package (https://github.com/neovim/python-client/blob/0.1.13/neovim/__init__.py#L24)?

In my neovim bundle for windows python 3 is embedded with neovim-client package. It means that neovim-client package located into zip file that also included all python std library (python35.zip). That is why the current detection version method not appropriate for this case and deoplete doesn't work.

**Comment by tweekmonster** [comment]
That's a recent addition to the neovim module.  It could be an additional check *now*, but it wouldn't be wise to replace the current method since we can't guarantee neovim-python will be a version that has that variable in distro packages.

The `pkg_resources` method should work even with zipped modules unless you don't have `setuptools` installed.  Why is neovim-client in the zip file anyways?

**Comment by standeck** [comment]
My goal is minimized, self contained bundle of neovim for windows. That is why the neovim-client in zip file without other stuff from python ecosystem like setuptools. Of course, problem solves by using standard way organization of python packages, but I like minimum requirements packed into zip file.

This added support checking version from new VERSION variable: https://github.com/standeck/deoplete.nvim/commit/3c49b7bed114d24f68694c2623424f38755c64e5.

**Comment by tweekmonster** [comment]
> My goal is minimized, self contained bundle of neovim for windows.

Fair enough.  But, that means you'd have to recreate it to upgrade things right?

> This added support checking version from new VERSION variable: standeck@3c49b7b.

The method for getting the version looks good to me.  You should submit a PR.  But, I think @Shougo might prefer if that was an instance method instead of outside the class scope.  I also think it might be better if that check happened in the exception before the final fallback method.  The neovim module's `setup.py` is bumped separately and would be more consistent with the original version formatting: https://github.com/neovim/python-client/blob/master/setup.py#L25

**Comment by standeck** [comment]
> Fair enough. But, that means you'd have to recreate it to upgrade things right?
Yes, it required recreating bundle if neovim-client updated. But I do not plane update only for "keep fresh", and with some kind of automation made process easier.

I did create the pull request based on the comments above.
