### ISSUE TITLE
Deoplete very slow

### ISSUE THREAD

**Issue by juanes852** [Shougo/deoplete.nvim#62]
Hi,
With a old computer (1 GB of RAM, 1,6Ghz, 512 KB cache memory CPU), Deoplete is very slow. With a new file « .java », or « .c », when I write quickly « main », I haven't popup menu. I have to write only « mai », and wait to have the popup menu ; when I write « main » I haven't popu menu even if I wait. With Neocomplete in Vim, I haven't this problem. Of course, I've tried with a minimalistic .vimrc. With a better computer, I haven't this problem. It's strange, because Deoplete should be faster than NeoComplete ?

**Comment by Shougo** [comment]
It is feature.  Because, deoplete is slower than neocomplete.
deoplete is real asynchronous plugin.
The asynchronous is to skip the completion if you input the characters.
You should upgrade the machine to use deoplete and neovim.
neocomplete is synchronous plugin.  So, it generates candidates in the slow machine.
