### ISSUE TITLE
deoplete#custom#option() implementation

### ISSUE THREAD

**Issue by Shougo** [Shougo/deoplete.nvim#707]
I will add `deoplete#custom#option()` API for deoplete customization like denite.nvim.

It replaces almost all deoplete variables.
`g:deoplete#enable_yarp`, `g:deoplete#complete_method` etc.

It will be implemented after #682.

**Comment by Shougo** [comment]
It is already implemented.

**Comment by kevinushey** [comment]
Would you be willing to make the documentation a bit more explicit on how these options are used? If I understand correctly, `g:deoplete#enable_at_startup = 1` is now the only 'global' option to be set, but others are now set through `deoplete#custom#option()`.

Am I correct that all of the options as defined in https://github.com/Shougo/deoplete.nvim/blob/master/doc/deoplete.txt#L83 should now be toggled through the use of `deoplete#custom#option()`? If so, it would be nice if that were declared up-front.

In addition, I guess these options cannot be set directly from the `.vimrc` since `deoplete` may not be loaded yet (at least it did not work for me with Vim 8). Is the recommended way to do this in `VimEnter` or something similar?

Thanks for the awesome plugin!

**Comment by Shougo** [comment]
deoplete initialization works before VimEnter.
Note: you need to add runtimepath though.
