### ISSUE TITLE
Auto-insertion of first suggestion not happening

### ISSUE THREAD

**Issue by tgy** [Shougo/deoplete.nvim#810]
# Problems summary

I can't get the auto-insertion of the first suggestion to work. It's only selected but not inserted.

## Expected

I expected the auto-insertion feature to work. I expected the first suggestion to be directly inserted.

## Environment Information

 * deoplete version (SHA1): `6b377491a77f5ac30b700cdccd18d1fe38d66894`

 * OS: macOS High Sierra 10.13.6

 * neovim/Vim `:version` output:

```
NVIM v0.3.0
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20180612-71518-1f95nfa/neovim-0.3.0/build/config -I/tmp/neovim-20180612-71518-1f95nfa/neovim-0.3.0/src -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20180612-71518-1f95nfa/neovim-0.3.0/build/src/nvim/auto -I/tmp/neovim-20180612-71518-1f95nfa/neovim-0.3.0/build/include
Compiled by brew@HighSierra.local

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.3.0/share/nvim"

Run :checkhealth for more info
```

 * `:checkhealth` or `:CheckHealth` result(neovim only):

```

health#jedi#check
========================================================================
## jedi
#### Jedi-vim debug information
Using Python version: 3
 - global sys.version: `3.6.5 |Anaconda, Inc.| (default, Apr 26 2018, 08:42:37), [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]`
 - global site module: `/Users/viovene/miniconda3/lib/python3.6/site.py`
Jedi path: `/Users/viovene/.local/share/nvim/plugged/jedi-vim/pythonx/jedi/jedi/__init__.py`
 - version: 0.12.0
 - environment: `<Environment: 3.6.5 in /Users/viovene/miniconda3>`
 - sys_path:
    - `/Users/viovene/miniconda3/lib/python36.zip`
    - `/Users/viovene/miniconda3/lib/python3.6`
    - `/Users/viovene/miniconda3/lib/python3.6/lib-dynload`
    - `/Users/viovene/miniconda3/lib/python3.6/site-packages`
    - `/Users/viovene/projects/neurolang`
 - jedi-vim git version: 7cade1f
 - jedi git submodule status:  bd7c65d9639c2d451d44c6d135b4f6043a918950 pythonx/jedi (v0.12.0)
 - parso git submodule status:  e6bc924fbabbfa3090044e475c91a7655b9c6e9b pythonx/parso (v0.3.1)


##### Settings
g:jedi#auto_vim_configuration = 0 (default: 1)
g:jedi#smart_auto_mappings = 0 (default: 1)
g:jedi#show_call_signatures = 0 (default: 1)
g:jedi#completions_enabled = 0 (default: 1)


  omnifunc=htmlcomplete#CompleteTags
	Last set from /usr/local/Cellar/neovim/0.3.0/share/nvim/runtime/ftplugin/html.vim
  completeopt=menu,preview,noinsert
	Last set from ~/.config/nvim/init.vim

health#deoplete#check
========================================================================
## deoplete.nvim
  - OK: has("nvim") was successful
  - OK: exists("v:t_list") was successful
  - OK: has("timers") was successful
  - OK: has("python3") was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $TERM_PROGRAM='iTerm.app'
  - INFO: $COLORTERM='truecolor'

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: pbcopy

## Python 2 provider (optional)
  - WARNING: No Python interpreter was found with the neovim module.  Using the first available for diagnostics.
  - ERROR: Python provider error
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          /usr/local/bin/python2 does not have the "neovim" module. :help |provider-python|
          /usr/local/bin/python2.7 does not have the "neovim" module. :help |provider-python|
          python2.6 not found in search path or not executable.
          /Users/viovene/miniconda3/bin/python is Python 3.6 and cannot provide Python 2.
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Multiple python3 executables found.  Set `g:python3_host_prog` to avoid surprises.
  - INFO: Executable: /Users/viovene/miniconda3/bin/python3
  - INFO: Other python executable: /usr/local/bin/python3
  - INFO: Python3 version: 3.6.5
  - INFO: python3-neovim version: 0.2.6
  - OK: Latest python3-neovim is installed: 0.2.6

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin17]
  - WARNING: `neovim-ruby-host` not found.
    - ADVICE:
      - Run `gem install neovim` to ensure the neovim RubyGem is installed.
      - Run `gem environment` to ensure the gem bin directory is in $PATH.
      - If you are using rvm/rbenv/chruby, try "rehashing".
      - See :help |g:ruby_host_prog| for non-standard gem installations.

## Node.js provider (optional)
  - WARNING: `node` and `npm` must be in $PATH.
    - ADVICE:
      - Install Node.js and verify that `node` and `npm` commands work.
```

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
call plug#begin('~/.local/share/nvim/plugged')

" autocompletion
Plug 'davidhalter/jedi-vim'
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
Plug 'zchee/deoplete-jedi', {'for': 'python'}

call plug#end()

set nocompatible
filetype plugin indent on

syntax enable

set completeopt+=noinsert

let g:jedi#completions_enabled = 0
let g:jedi#auto_vim_configuration = 0
let g:jedi#smart_auto_mappings = 0
let g:jedi#show_call_signatures = 0

let g:deoplete#enable_at_startup = 1
let g:deoplete#sources = {}
let g:deoplete#sources.python = ['jedi']
let g:deoplete#sources#jedi#show_docstring = 1
```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. Open a Python file
2. Type in
    ```python
    import re
    re.
3. The first suggestion should be something like `re.compile`. It's not inserted, only selected in the list of suggestions.

## Screenshot (if possible)

<img width="762" alt="screen shot 2018-07-19 at 10 17 26" src="https://user-images.githubusercontent.com/694873/42930331-fb8fe046-8b3c-11e8-86ba-13cf8b2b1b7d.png">

**Comment by Shougo** [comment]
It is the feature of `noinsert`.
You should read `:help completeopt`.

And,

> I expected the auto-insertion feature to work. I expected the first suggestion to be directly inserted.

You should not in auto completion.
It breaks your input.

**Comment by kodonnell** [comment]
@Shougo I'm getting this behaviour with `completeopt=menu,preview` i.e. in the above case I'd expect 'compile' to be auto-inserted so that the preview window displays as-is, but the text now reads `re.compile` (i.e. `compile` after the cursor). However, you say this would break input - can you explain more (for me and future readers)? And can you clarify if this breaking is generic, or specific to deoplete/vim? I assume there are others that would wish to save <tab>s (or similar) when the completion is already right.

FYI - when I add `completeopt+=noinsert` the only change is the first time I hit <tab> the *second* option is displayed (e.g. `copyreg` here). If this is a separate issue, let me know and I'll file one.

**Comment by Shougo** [comment]
> However, you say this would break input - can you explain more (for me and future readers)?

Hm...  Really?  You should consider the issue more carefully.
If you input "com" and "compile" is first suggestion, the input will be "compile".
If you don't want to complete it to "compile", it breaks your inputted text.
If it is manual completion, I think it is OK.
But deoplete is auto completion plugin.  So it is not OK.
Auto completion works if you don't want to complete it.
You can change the behavior and know the break.
`deoplete#mapping#_set_completeopt()` changes `completeopt`.
You can disable it after modify the function.

> And can you clarify if this breaking is generic, or specific to deoplete/vim?

It is auto completion plugin feature not depends on deoplete.

**Comment by Shougo** [comment]
>FYI - when I add completeopt+=noinsert the only change is the first time I hit the second option is displayed (e.g. copyreg here).

It is feature of preview window.  I cannot fix it.

**Comment by kodonnell** [comment]
> If you input "com" and "compile" is first suggestion, the input will be "compile".

Not for me - I still have to hit tab. Are you saying this is unexpected behaviour?

![image](https://user-images.githubusercontent.com/8204904/46920666-4943b280-d04e-11e8-8bdb-392a7f2ad240.png)

I'd expect this (changes in red):

![image](https://user-images.githubusercontent.com/8204904/46920701-a9d2ef80-d04e-11e8-8679-18b5a2fd9410.png)

I only get that after hitting tab once.

> If you don't want to complete it to "compile", it breaks your inputted text.

I was expecting that in this scenario, if say the second option was 'comment' (which doesn't actually exist in `re` but let's pretend), which I wanted, then I'd just hit tab once, and get 're.comment'. I.e. first:

![image](https://user-images.githubusercontent.com/8204904/46920741-409fac00-d04f-11e8-8950-84dd448f4854.png)

Then hit tab:

![image](https://user-images.githubusercontent.com/8204904/46920753-5b722080-d04f-11e8-87f0-4bb2d67139aa.png)

This is what currently happens when you hit tab - depending on `noinsert` - (it's just that `pile` isn't auto-inserted first).

> If it is manual completion, I think it is OK.

But when I hit tab, it does auto-insert the selected option. E.g. after typing `re.com` and *hitting tab* I get: 

![image](https://user-images.githubusercontent.com/8204904/46920785-c02d7b00-d04f-11e8-95ec-1d2606ddd238.png)

I.e. it has already inserted `pile` for me. If this is already accepted behaviour (and doesn't break things) then I can't see why we can't auto-insert the first option too. 

To get the behaviour I want, I guess I could try to code something that automatically 'presses' tab once the completion window has opened, and hence auto-inserts the first option for me. Though that seems nasty, and like there are better ways to do it (and that it'd be a common use case for deoplete, so would have an easy option to do this).

FYI minimal init.vim:

```
set nocompatible
filetype plugin indent on
call plug#begin()
    Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
    Plug 'zchee/deoplete-jedi'
call plug#end()
let g:deoplete#enable_at_startup = 1
inoremap <expr><tab> pumvisible() ? "\<c-n>" : "\<tab>"
```

**Comment by Shougo** [comment]
OK.  I get it.
Unfortunately, I cannot implement the feature.
Because, Vim/neovim does not support the feature.
You should request the feature in neovim/Vim issues instead of deoplete.

**Comment by Shougo** [comment]
And this behavior only useful if the match is heading.
Fuzzy match is already implemented in deoplete.
